config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
import myapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('accounts/', include('allauth.urls')),
]  + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')), 
    path('', include('myapp.urls')),

)




myapp/urls.py
# from django.urls import path, include
# from rest_framework.routers import DefaultRouter
# from .views import PostViewSet

# router = DefaultRouter()
# router.register(r'posts', PostViewSet)

# urlpatterns = [
#     path('', include(router.urls)),
# ]

from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('index.html', views.home, name='index'),  
    path('profile/', views.profile, name='profile'),
    path('search/', views.home, name='search'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login', views.LoginView.as_view(), name='login'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_confirm/', views.password_reset_confirm, name='password_reset_confirm'),
    path('register/verify_email', views.VerifyEmailView.as_view(), name='verify_email'),
    path('logout', views.LogoutView.as_view(), name='logout'), 
    path('category/<int:category_id>/', views.articles_by_category, name='articles_by_category'),
    path('turinfo/<int:place_id>/', views.turinfo, name='turinfo'),
    path('rate_place/<int:place_id>/', views.rate_place, name='rate_place'),
    path('like/<int:article_id>/', views.like_article, name='like_article'),
    path('add_to_cart/<int:article_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:article_id>/', views.remove_from_cart, name='remove_from_cart'),  
    path('cart/', views.cart_view, name='cart_view'),
    path('profile/', views.profile_view, name='profile'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser, PermissionsMixin, Permission, Group
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password

from django.conf import settings 

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    max_articles_per_category = models.SmallIntegerField(default=3)

    def __str__(self):
        return self.name
    

class Article(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='articles')
    title = models.CharField(max_length=200)
    text = models.TextField()
    img = models.ImageField(upload_to='tourism_images/')
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    

class Reclama(models.Model):
    title = models.CharField(max_length=100)
    img = models.ImageField(upload_to='reklama/')

    def __str__(self):
        return self.title

from django.db.models import Avg
class TourismPlace(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    duration = models.CharField(max_length=80, null=True, default=0)  
    places_count = models.CharField(max_length=80, null=True, default=0)
    views = models.PositiveIntegerField(default=0)  
    phone_number = models.CharField(max_length=20, blank=True, null=True) 

    def upload_to(instance, filename):
        return 'tourism_images/{filename}'.format(filename=filename)
    
    img = models.ImageField(upload_to=upload_to)

    def average_rating(self):
        return self.ratings.aggregate(Avg('stars'))['stars__avg'] or 0
    
    def rating_count(self):
        return self.ratings.count()

    def __str__(self):
        return self.title
    


class TourismPlaceImage(models.Model):
    
    place = models.ForeignKey(TourismPlace, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='tourism_images/')

    def __str__(self):
        return f"Image for {self.place.title}"
    


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user( email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user( email, password, **extra_fields)


class User(AbstractUser, PermissionsMixin):
    username = None
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    accounts_type = models.CharField(max_length=15)
    email = models.EmailField(unique=True)
    gender = models.CharField(max_length=10)
    

    objects = CustomUserManager()

    def __str__(self):
        return self.email

from django.utils import timezone

class TemporaryAccountData(models.Model):
    first_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=128)
    accounts_type = models.CharField(max_length=15)
    gender = models.CharField(max_length=10)
    verification_code = models.CharField(max_length=6)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    

    def __str__(self):
        return self.email
    


from django.core.validators import MinValueValidator, MaxValueValidator
class Rating(models.Model):
    place = models.ForeignKey(TourismPlace, related_name="ratings", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stars = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = [['user', 'place']]

    def __str__(self):
        return f"{self.stars} stars by {self.user.email} for {self.place.title}"

class Comment(models.Model):
    place = models.ForeignKey(TourismPlace, related_name="comments", on_delete=models.CASCADE) 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  
    text = models.TextField()  
    created_at = models.DateTimeField(default=timezone.now) 
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies', null=True, blank=True)
    def __str__(self):
        return f"Comment by {self.user.first_name} on {self.place.title}"




class Like(models.Model):
    article = models.ForeignKey(Article, related_name='likes', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='likes', on_delete=models.CASCADE)
    liked = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.user.username} liked {self.article.title}"


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    articles = models.ManyToManyField(Article, through='CartItem')
    created_at = models.DateTimeField(default=timezone.now)

    # For add to card
    duration = models.CharField(max_length=80, null=True, default=0)  
    places_count = models.CharField(max_length=80, null=True, default=0)
    views = models.PositiveIntegerField(default=0)  
    phone_number = models.CharField(max_length=20, blank=True, null=True) 

    def __str__(self):
        return f"{self.user}"  

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    added_at = models.DateTimeField(default=timezone.now)

templates/registerPage/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kabinet</title>
</head>
<body>
    <h1>Xush kelibsiz!</h1>
    <p id="welcomeMessage">Siz muvaffaqiyatli tizimga kirdingiz.</p>
    <button id="logoutBtn">Chiqish</button>

    <script src="./dashboard.js"></script>
</body>
</html>

templates/registerPage/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ro'yxatdan O'tish</title>
</head>
<style>
  header{
    display: none;
  }
  body {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background-color: #9BBAD3;
  }

  body,
  div,
  dl,
  dt,
  dd,
  ul,
  ol,
  li,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  pre,
  form,
  fieldset,
  input,
  textarea,
  p,
  blockquote,
  th,
  td {
    padding: 0;
    margin: 0;
  }

  fieldset,
  img {
    border: 0
  }

  ol,
  ul,
  li {
    list-style: none
  }

  :focus {
    outline: none
  }

  body,
  input,
  textarea,
  select {
    font-family: 'Open Sans', sans-serif;
    font-size: 16px;
    color: #4c4c4c;
  }

  p {
    font-size: 12px;
    width: 150px;
    display: inline-block;
    margin-left: 18px;
  }

  h1 {
    font-size: 32px;
    font-weight: 300;
    color: #4c4c4c;
    text-align: center;
    padding-top: 10px;
    margin-bottom: 10px;
  }

  html {
    background-color: #ffffff;
  }

  .testbox {
    margin: 20px auto;
    width: 343px;
    /* height: 464px;  */
    -webkit-border-radius: 8px/7px;
    -moz-border-radius: 8px/7px;
    border-radius: 8px/7px;
    background-color: #ebebeb;
    -webkit-box-shadow: 1px 2px 5px rgba(0, 0, 0, .31);
    -moz-box-shadow: 1px 2px 5px rgba(0, 0, 0, .31);
    box-shadow: 1px 2px 5px rgba(0, 0, 0, .31);
    border: solid 1px #cbc9c9;
  }

  input[type=radio] {
    visibility: hidden;
  }

  form {
    margin: 0 30px;
  }

  label.radio {
    cursor: pointer;
    text-indent: 35px;
    overflow: visible;
    display: inline-block;
    position: relative;
    margin-bottom: 15px;
  }

  label.radio:before {
    background: #3a57af;
    content: '';
    position: absolute;
    top: 2px;
    left: 0;
    width: 20px;
    height: 20px;
    border-radius: 100%;
  }

  label.radio:after {
    opacity: 0;
    content: '';
    position: absolute;
    width: 0.5em;
    height: 0.25em;
    background: transparent;
    top: 7.5px;
    left: 4.5px;
    border: 3px solid #ffffff;
    border-top: none;
    border-right: none;

    -webkit-transform: rotate(-45deg);
    -moz-transform: rotate(-45deg);
    -o-transform: rotate(-45deg);
    -ms-transform: rotate(-45deg);
    transform: rotate(-45deg);
  }

  input[type=radio]:checked+label:after {
    opacity: 1;
  }

  hr {
    color: #a9a9a9;
    opacity: 0.3;
  }

  input[type=text],
  input[type=email],
  input[type=password] {
    width: 200px;
    height: 39px;
    -webkit-border-radius: 0px 4px 4px 0px/5px 5px 4px 4px;
    -moz-border-radius: 0px 4px 4px 0px/0px 0px 4px 4px;
    border-radius: 0px 4px 4px 0px/5px 5px 4px 4px;
    background-color: #fff;
    -webkit-box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    -moz-box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    border: solid 1px #cbc9c9;
    margin-left: -5px;
    margin-top: 13px;
    padding-left: 10px;
  }

  input[type=password] {
    margin-bottom: 25px;
  }

  #icon {
    display: inline-block;
    width: 30px;
    background-color: #3a57af;
    padding: 8px 0px 8px 15px;
    margin-left: 15px;
    -webkit-border-radius: 4px 0px 0px 4px;
    -moz-border-radius: 4px 0px 0px 4px;
    border-radius: 4px 0px 0px 4px;
    color: white;
    -webkit-box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    -moz-box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    border: solid 0px #cbc9c9;
  }

  .gender {
    margin-left: 30px;
    margin-right: 30px;

    margin-bottom: 30px;
  }

  .accounttype {
    margin-left: 8px;
    margin-top: 20px;
  }
  .btnwrap{
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
}
  button {
    margin: 0 auto;

    font-size: 14px;
    font-weight: 600;
    color: white;
    padding: 6px 25px 5px 20px;
    margin: 10px 8px 20px 0px;
    display: block;
    /* display: inline-block; */
    /* float: center; */
    text-decoration: none;
    width: 100px;
    height: 27px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
    background-color: #3a57af;
    -webkit-box-shadow: 0 3px rgba(58, 87, 175, .75);
    -moz-box-shadow: 0 3px rgba(58, 87, 175, .75);
    box-shadow: 0 3px rgba(58, 87, 175, .75);
    transition: all 0.1s linear 0s;
    left: 50%;
    border: none;
    /* top: 0px;
  position: relative; */
  }

  button:hover {
    top: 3px;
    background-color: #2e458b;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;

  }
  .forgotp{
    margin-bottom: 10px;
    text-decoration: none;
  }
  .logreg{
  width: 100%;
  text-align: center;
  display: flex;
  justify-content: center;
  margin-bottom: 10px;
  color: #9BBAD3;
  text-decoration: none;
}
.logreg:hover{
  color:#228ee7 ;
}
</style>

<body>
  {% include 'header.html' %}
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600' rel='stylesheet'
    type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css" rel="stylesheet">

  <div class="testbox">
    <h1 id="loginlink">Kirish</h1>
    {% if error %}
    <div style="color: red;">{{ error }}</div> <!-- Xatoliklar uchun joy -->
    {% endif %}
    <form action="{% url 'login' %}" method="post">
      {% csrf_token %}
      <label id="icon" for="email"><i class="icon-envelope"></i></label>
      <input type="email" name="email" id="email" placeholder="Elektron pochta" required />
      <label id="icon" for="password"><i class="icon-shield"></i></label>
      <input type="password" name="password" id="id_password" placeholder="Parol" required />
      <div class="btnwrap">
        <button type="submit" class="button" id="loginlink">Kirish</button>
      <a class="forgotp" id="forgotp" href="{% url 'password_reset' %}">Parolni unutdingizmi?</a>
      </div>
      <a class="logreg" id="registerb"  href="{% url 'register' %}">Ro'yhatdan o'tish</a>

    </form>

  </div>
</body>

</html>

templates/registerPage/register.html
<!DOCTYPE html>{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>Ro'yxatdan O'tish</title>
</head>
<style>
  header {
    display: none;
  }

  body {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background-color: #9BBAD3;
  }

  body,
  div,
  dl,
  dt,
  dd,
  ul,
  ol,
  li,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  pre,
  form,
  fieldset,
  input,
  textarea,
  p,
  blockquote,
  th,
  td {
    padding: 0;
    margin: 0;
  }


  fieldset,
  img {
    border: 0
  }

  ol,
  ul,
  li {
    list-style: none
  }

  :focus {
    outline: none
  }

  body,
  input,
  textarea,
  select {
    font-family: 'Open Sans', sans-serif;
    font-size: 16px;
    color: #4c4c4c;
  }

  p {
    font-size: 12px;
    width: 150px;
    display: inline-block;
    margin-left: 18px;
  }

  h1 {
    font-size: 32px;
    font-weight: 300;
    color: #4c4c4c;
    text-align: center;
    padding-top: 10px;
    margin-bottom: 10px;
  }

  html {
    background-color: #ffffff;
  }

  .testbox {
    margin: 20px auto;
    width: 343px;
    /* height: 464px;  */
    -webkit-border-radius: 8px/7px;
    -moz-border-radius: 8px/7px;
    border-radius: 8px/7px;
    background-color: #ebebeb;
    -webkit-box-shadow: 1px 2px 5px rgba(0, 0, 0, .31);
    -moz-box-shadow: 1px 2px 5px rgba(0, 0, 0, .31);
    box-shadow: 1px 2px 5px rgba(0, 0, 0, .31);
    border: solid 1px #cbc9c9;
  }

  input[type=radio] {
    visibility: hidden;
  }

  form {
    margin: 0 30px;
  }

  label.radio {
    cursor: pointer;
    text-indent: 35px;
    overflow: visible;
    display: inline-block;
    position: relative;
    margin-bottom: 15px;
  }

  label.radio:before {
    background: #3a57af;
    content: '';
    position: absolute;
    top: 2px;
    left: 0;
    width: 20px;
    height: 20px;
    border-radius: 100%;
  }

  label.radio:after {
    opacity: 0;
    content: '';
    position: absolute;
    width: 0.5em;
    height: 0.25em;
    background: transparent;
    top: 7.5px;
    left: 4.5px;
    border: 3px solid #ffffff;
    border-top: none;
    border-right: none;

    -webkit-transform: rotate(-45deg);
    -moz-transform: rotate(-45deg);
    -o-transform: rotate(-45deg);
    -ms-transform: rotate(-45deg);
    transform: rotate(-45deg);
  }

  input[type=radio]:checked+label:after {
    opacity: 1;
  }

  hr {
    color: #a9a9a9;
    opacity: 0.3;
  }

  input[type=text],
  input[type=email],
  input[type=password] {
    width: 200px;
    height: 39px;
    -webkit-border-radius: 0px 4px 4px 0px/5px 5px 4px 4px;
    -moz-border-radius: 0px 4px 4px 0px/0px 0px 4px 4px;
    border-radius: 0px 4px 4px 0px/5px 5px 4px 4px;
    background-color: #fff;
    -webkit-box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    -moz-box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    border: solid 1px #cbc9c9;
    margin-left: -5px;
    margin-top: 13px;
    padding-left: 10px;
  }

  input[type=password] {
    margin-bottom: 25px;
  }

  #icon {
    display: inline-block;
    width: 30px;
    background-color: #3a57af;
    padding: 8px 0px 8px 15px;
    margin-left: 15px;
    -webkit-border-radius: 4px 0px 0px 4px;
    -moz-border-radius: 4px 0px 0px 4px;
    border-radius: 4px 0px 0px 4px;
    color: white;
    -webkit-box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    -moz-box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    box-shadow: 1px 2px 5px rgba(0, 0, 0, .09);
    border: solid 0px #cbc9c9;
  }

  .gender {
    margin-left: 30px;
    margin-bottom: 30px;
  }

  .accounttype {
    margin-left: 8px;
    margin-top: 20px;
  }

  .regbtn__Wrapper {
    width: 100%;
    display: grid;
    grid-template-columns: 1fr 1fr;

  }

  .regbtn__Wrapper p {
    cursor: pointer;
  }

  .btn {
    font-size: 14px;
    font-weight: 600;
    color: white;
    padding: 6px 25px 0px 20px;
    margin: 10px 8px 20px 0px;
    display: inline-block;
    float: right;
    text-decoration: none;
    /* width: 50px; height: 27px;  */
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
    background-color: #3a57af;
    -webkit-box-shadow: 0 3px rgba(58, 87, 175, .75);
    -moz-box-shadow: 0 3px rgba(58, 87, 175, .75);
    box-shadow: 0 3px rgba(58, 87, 175, .75);
    transition: all 0.1s linear 0s;
    top: 0px;
    position: relative;
    border: none;
    cursor: pointer;
  }

  .btn:hover {
    top: 3px;
    background-color: #2e458b;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;

  }

  .reglog {
    width: 100%;
    text-align: center;
    display: flex;
    justify-content: center;
    margin-bottom: 10px;
    color: #9BBAD3;
    text-decoration: none;
  }

  .reglog:hover {
    color: #228ee7;
  }
</style>

<body>
  {% include 'header.html' %}
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600' rel='stylesheet'
    type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css" rel="stylesheet">
  <div class="testbox">
    <h1 id="register__title">Ro'yhatdan o'tish</h1>
    {% if error %}
    <div style="color: red;">{{ error }}</div>
    {% endif %}
    <form action="{% url 'register' %}" method="post">
      {% csrf_token %}
      <hr>
      <div name="accounts" id="id_accounts_type" class="accounttype">
        <input type="radio" value="person" id="radioOne" name="accounts_type" />
        <label id="Physical" for="radioOne" class="radio" chec>Jismoniy</label>
        <input type="radio" value="company" id="radioTwo" name="accounts_type" required />
        <label id="Legal" for="radioTwo" class="radio">Yuridik</label>
      </div>
      <hr>
      <label id="icon" for="name"><i class="icon-user"></i></label>
      <input type="text" name="first_name" id="username" placeholder="Ism" required />
      <label id="icon" for="name"><i class="icon-envelope "></i></label>
      <input type="email" name="email" id="email" placeholder="Elektron pochta" required />

      <label id="icon" for="name"><i class="icon-shield"></i></label>
      <input type="password" name="password" id="id_password" placeholder="Parol" minlength="6" required />
      <div class="gender" name="gender" id="id_gender">
        <input type="radio" value="male" id="male" name="gender" />
        <label id="malee" for="male" class="radio" chec>Erkak</label>
        <input id="female" type="radio" value="female" id="female" name="gender" required />
        <label id="femalee" for="female" class="radio">Ayol</label>
      </div>
      <div class="regbtn__Wrapper">
        <p id="terms">Ro'yhatdan o'tish orqali bizningqoidalarga roziligingizni bildirasiz.</p>
        <button id="registerb" href="./login.html" class="btn" type="submit">Ro'yhatdan o'tish</button>
      </div>
      <a class="reglog" id="loginlink" href="{% url 'login' %}">Kirish</a>
    </form>
  </div>

  <script src="{% static 'app.js' %}"></script>
</body>

</html>